#!/usr/bin/env php
<?php

use CodesVault\Bundle\Bundler;

require __DIR__ . "/vendor/autoload.php";

$bundler = new Bundler(__DIR__);

$bundler
    ->createProductionRepo('welcome')
    ->command("npm run build")
    ->cleanUp()
    ->zip('welcome')
    ->executionTime();
